## Урок 2. Матрицы и матричные операции

### Матрицы и матричные операции. Часть 1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.


__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;


__Решение__

Произведение матриц $AB$ НЕ определено.

Произведение матриц $BA$ НЕ определено.

    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;


__Решение__

Произведение матриц $AB$ определено и размерность полученной матрицы $2\times 3$.

Произведение матриц $BA$ НЕ определено.

    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;


__Решение__

Произведение матриц $AB$ определено и размерность полученной матрицы $8\times 8$.

Произведение матриц $BA$ определено и размерность полученной матрицы $3\times 3$.

    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.


__Решение__

Произведение матриц $AB$ определено и размерность полученной матрицы $4\times 4$.

Произведение матриц $BA$ определено и размерность полученной матрицы $4\times 4$.

    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


__Решение__

Сумма матриц:
$A + B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} +
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0 + 5
\end{pmatrix} =
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}
$


Произведение матриц:
$A \cdot B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1\cdot4-2\cdot0 & 1\cdot(-1)-2\cdot5\\ 
3\cdot4+0\cdot0 & 3\cdot(-1) + 0\cdot5
\end{pmatrix} =
\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}
$

In [6]:
import numpy as np
A = np.array([[1, -2],
              [3, 0]])
B = np.array([[4, -1], 
              [0, 5]])

In [7]:
A+B

array([[ 5, -3],
       [ 3,  5]])

In [8]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$


__Решение__

$3A-2B+4C =
3 \cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} -
2 \cdot
\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 
4 \cdot
\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} =
\begin{pmatrix}
3\cdot1 & 3\cdot7\\ 
3\cdot3 & 3\cdot(-6)
\end{pmatrix} -
\begin{pmatrix}
2\cdot0 & 2\cdot5\\ 
2\cdot2 & 2\cdot(-1)
\end{pmatrix} + 
\begin{pmatrix}
4\cdot2 & 4\cdot(-4)\\ 
4\cdot1 & 4\cdot1
\end{pmatrix} =$

$
= \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} -
\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + 
\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} =
\begin{pmatrix}
3-0+8 & 21-10+(-16)\\ 
9-4+4 & -18-(-2)+4
\end{pmatrix} =
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}
$

In [9]:
A = np.array([[1, 7],
              [3, -6]])
B = np.array([[0, 5], 
              [2, -1]])
C = np.array([[2, -4], 
              [1, 1]])

In [10]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


__Решение__

$AA^{T} = 
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} =
\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\ 
5\cdot4-2\cdot1 & 5\cdot5-2\cdot(-2) & 5\cdot2-2\cdot3\\ 
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix} =
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}
$

$A^{T}A =
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} =
\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4-2\cdot5+3\cdot2 & 1\cdot1-2\cdot(-2)+3\cdot3
\end{pmatrix} =
\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}
$

In [11]:
A = np.array([[4, 1],
              [5, -2],
              [2, 3]])

In [13]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [14]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [38]:
def dotmatrix(A, B):
    if A.shape[1] != B.shape[0]:
        print('Произведение матриц НЕ определено')
        return
    else:
        print('Произведение матриц определено')
        C = np.zeros((A.shape[0], B.shape[1]), dtype=int)
        for i in range(C.shape[0]):
            for j in range(C.shape[1]):
                for k in range(A.shape[1]):
                    C[i, j] += A[i, k]*B[k, j]
        return C

In [39]:
dotmatrix(A, A)

Произведение матриц НЕ определено


In [40]:
dotmatrix(A, A.T)

Произведение матриц определено


array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

### Матрицы и матричные операции. Часть 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;

    
   б) $det(A^{T})$;

    
   в) $det(2A)$.

   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$