## ДЗ к Уроку 6.
### Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.

### 1. Задание:

_Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):_

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

_Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas._

In [1]:
import numpy as np
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
# ковариация по формуле (смещенная)
cov = (zp * ks).mean() - zp.mean() * ks.mean()
cov

9157.839999999997

In [2]:
# несмещенная оценка ковариации
print(np.cov(zp, ks))
cov_1 = np.cov(zp, ks)[0,1]
cov_1

[[ 3882.93333333 10175.37777778]
 [10175.37777778 33854.32222222]]


10175.377777777776

In [3]:
# смещенная оценка ковариации
print(np.cov(zp, ks, ddof=0))
cov_2 = np.cov(zp, ks, ddof=0)[0,1]
cov_2

[[ 3494.64  9157.84]
 [ 9157.84 30468.89]]


9157.84

In [4]:
# несмещенные оценки стандартных отклонений и корреляции
s_1_1 = zp.std(ddof=1)
s_1_2 = ks.std(ddof=1)
corr_1 = cov_1 / (s_1_1 * s_1_2)
s_1_1, s_1_2, corr_1

(62.31318747531162, 183.99544076477068, 0.887490092073916)

In [5]:
# смещенные оценки стандартных отклонений и корреляции
s_2_1 = zp.std()
s_2_2 = ks.std()
corr_2 = cov_2 / (s_2_1 * s_2_2)
s_2_1, s_2_2, corr_2

(59.115480206118605, 174.55340157098058, 0.8874900920739162)

In [6]:
print(np.corrcoef(zp, ks))
np.corrcoef(zp, ks)[0,1]

[[1.         0.88749009]
 [0.88749009 1.        ]]


0.8874900920739162

### 2. Задание:

_Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:_

131, 125, 115, 122, 131, 115, 107, 99, 125, 111.

_Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95._

In [7]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
n = len(iq) # = 10
v = n - 1 # = 9
a = 1 - 0.95 # = 0.05
a_2 = a / 2 # = 0.025
M = iq.mean() # = 118.1
t = 2.262 # для v=9 и a_2=0.025
S = iq.std(ddof=1) # = 10.54
T_1 = M - t * S / n**0.5
T_2 = M + t * S / n**0.5
iq, n, v, a, a_2, M, t, S, T_1, T_2

(array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111]),
 10,
 9,
 0.050000000000000044,
 0.025000000000000022,
 118.1,
 2.262,
 10.54566788359614,
 110.55660776308164,
 125.64339223691834)

### 3. Задание:

_Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95._

In [8]:
D = 25
S = D**0.5 # = 5
n = 27
M = 174.2
a = 1 - 0.95 # = 0.05
a_2 = a / 2 # = 0.025
Z = 1.96 # для a_2=0.025
T_1 = M - Z * S / n**0.5
T_2 = M + Z * S / n**0.5
D, S, n, M, a, a_2, Z, T_1, T_2

(25,
 5.0,
 27,
 174.2,
 0.050000000000000044,
 0.025000000000000022,
 1.96,
 172.31398912064722,
 176.08601087935276)

### 4. Задание:

_Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики
и напишите ее в комментарии к Практическому заданию.
Предлагаем взять данные с сайта imdb.com_

In [9]:
# Тема проекта "Статистическое исследование базы фильмов". Данные будут взяты с imdb.com.